First review m2s2
zoomkolol/react-stellar-burger pull request #4
Opened 2023-11-11 12:55 UTC by zoomkolol

2023-11-11 13:35 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Хорошая организация хранилища
- Содержимое конструктора очищается после оформления заказа
- Созданы все необходимые экшены

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- Генерировать уникальный id нужно в специальном колбеке preapare.
https://redux-toolkit.js.org/api/createAction#using-prepare-callbacks-to-customize-action-contents

- Сортировка работает не очень корректно. Пожалуйста посоветуйтесь с наставником.
https://github.com/zoomkolol/react-stellar-burger/assets/60173362/7a3ca578-6032-486e-839e-07daf750cc60

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-11-11 13:35 UTC, andryxxa93 commented on src/app/app.jsx
> +        <AppHeader />
**Можно лучше**
AppHeader не нужно оборачивать в `DndProvider `

2023-11-11 13:35 UTC, andryxxa93 commented on src/components/ingredient/ingredient.jsx
> +  const burgerConstructorData = useSelector(state => state.burgerConstructor);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-11-12 09:55 UTC, zoomkolol commented
Наставник сказал поменять индексы местами (в редьюсере), у него всё заработало.

2023-11-12 14:06 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-11-12 15:34 UTC, merged